# Generated by Django 4.0.5 on 2022-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default='2022-07-17', editable=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default='2022-07-17', editable=False),
        ),
    ]
